(************************************************************
 * WARNING!
 *
 * This file is generated by ocamlrpcgen from the source file
 * netplex_ctrl.x
 *
 ************************************************************)
module Control : sig
  module V1 : sig
    open Netplex_ctrl_aux
    val bind :
            ?program_number:Rtypes.uint4 ->
            ?version_number:Rtypes.uint4 ->
            proc_ping : (t_Control'V1'ping'arg -> t_Control'V1'ping'res) ->
            proc_poll : (t_Control'V1'poll'arg -> t_Control'V1'poll'res) ->
            proc_accepted : (t_Control'V1'accepted'arg ->
                             t_Control'V1'accepted'res) ->
            Rpc_server.t ->
            unit
    val bind_async :
            ?program_number:Rtypes.uint4 ->
            ?version_number:Rtypes.uint4 ->
            proc_ping : (Rpc_server.session ->
                         t_Control'V1'ping'arg ->
                         (t_Control'V1'ping'res -> unit) ->
                         unit) ->
            proc_poll : (Rpc_server.session ->
                         t_Control'V1'poll'arg ->
                         (t_Control'V1'poll'res -> unit) ->
                         unit) ->
            proc_accepted : (Rpc_server.session ->
                             t_Control'V1'accepted'arg ->
                             (t_Control'V1'accepted'res -> unit) ->
                             unit) ->
            Rpc_server.t ->
            unit
    end
  
end

module System : sig
  module V1 : sig
    open Netplex_ctrl_aux
    val bind :
            ?program_number:Rtypes.uint4 ->
            ?version_number:Rtypes.uint4 ->
            proc_ping : (t_System'V1'ping'arg -> t_System'V1'ping'res) ->
            proc_lookup : (t_System'V1'lookup'arg -> t_System'V1'lookup'res) ->
            proc_send_message : (t_System'V1'send_message'arg ->
                                 t_System'V1'send_message'res) ->
            proc_log : (t_System'V1'log'arg -> t_System'V1'log'res) ->
            Rpc_server.t ->
            unit
    val bind_async :
            ?program_number:Rtypes.uint4 ->
            ?version_number:Rtypes.uint4 ->
            proc_ping : (Rpc_server.session ->
                         t_System'V1'ping'arg ->
                         (t_System'V1'ping'res -> unit) ->
                         unit) ->
            proc_lookup : (Rpc_server.session ->
                           t_System'V1'lookup'arg ->
                           (t_System'V1'lookup'res -> unit) ->
                           unit) ->
            proc_send_message : (Rpc_server.session ->
                                 t_System'V1'send_message'arg ->
                                 (t_System'V1'send_message'res -> unit) ->
                                 unit) ->
            proc_log : (Rpc_server.session ->
                        t_System'V1'log'arg ->
                        (t_System'V1'log'res -> unit) ->
                        unit) ->
            Rpc_server.t ->
            unit
    end
  
end

module Admin : sig
  module V1 : sig
    open Netplex_ctrl_aux
    val bind :
            ?program_number:Rtypes.uint4 ->
            ?version_number:Rtypes.uint4 ->
            proc_ping : (t_Admin'V1'ping'arg -> t_Admin'V1'ping'res) ->
            proc_list : (t_Admin'V1'list'arg -> t_Admin'V1'list'res) ->
            proc_enable : (t_Admin'V1'enable'arg -> t_Admin'V1'enable'res) ->
            proc_disable : (t_Admin'V1'disable'arg -> t_Admin'V1'disable'res) ->
            proc_restart : (t_Admin'V1'restart'arg -> t_Admin'V1'restart'res) ->
            proc_restart_all : (t_Admin'V1'restart_all'arg ->
                                t_Admin'V1'restart_all'res) ->
            proc_shutdown : (t_Admin'V1'shutdown'arg ->
                             t_Admin'V1'shutdown'res) ->
            proc_reopen_logfiles : (t_Admin'V1'reopen_logfiles'arg ->
                                    t_Admin'V1'reopen_logfiles'res) ->
            proc_send_admin_message : (t_Admin'V1'send_admin_message'arg ->
                                       t_Admin'V1'send_admin_message'res) ->
            Rpc_server.t ->
            unit
    val bind_async :
            ?program_number:Rtypes.uint4 ->
            ?version_number:Rtypes.uint4 ->
            proc_ping : (Rpc_server.session ->
                         t_Admin'V1'ping'arg ->
                         (t_Admin'V1'ping'res -> unit) ->
                         unit) ->
            proc_list : (Rpc_server.session ->
                         t_Admin'V1'list'arg ->
                         (t_Admin'V1'list'res -> unit) ->
                         unit) ->
            proc_enable : (Rpc_server.session ->
                           t_Admin'V1'enable'arg ->
                           (t_Admin'V1'enable'res -> unit) ->
                           unit) ->
            proc_disable : (Rpc_server.session ->
                            t_Admin'V1'disable'arg ->
                            (t_Admin'V1'disable'res -> unit) ->
                            unit) ->
            proc_restart : (Rpc_server.session ->
                            t_Admin'V1'restart'arg ->
                            (t_Admin'V1'restart'res -> unit) ->
                            unit) ->
            proc_restart_all : (Rpc_server.session ->
                                t_Admin'V1'restart_all'arg ->
                                (t_Admin'V1'restart_all'res -> unit) ->
                                unit) ->
            proc_shutdown : (Rpc_server.session ->
                             t_Admin'V1'shutdown'arg ->
                             (t_Admin'V1'shutdown'res -> unit) ->
                             unit) ->
            proc_reopen_logfiles : (Rpc_server.session ->
                                    t_Admin'V1'reopen_logfiles'arg ->
                                    (t_Admin'V1'reopen_logfiles'res -> unit) ->
                                    unit) ->
            proc_send_admin_message : (Rpc_server.session ->
                                       t_Admin'V1'send_admin_message'arg ->
                                       (t_Admin'V1'send_admin_message'res -> unit) ->
                                       unit) ->
            Rpc_server.t ->
            unit
    end
  
end


